name: Frontend Tests

on:
  push:
  pull_request:

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci || npm install
      - name: test frontend
        run: |
          cd frontend
          npm run test
      - name: test frontend
        run: |
          cd frontend
          npm run coverage
